server:
  port: 8081

spring:
  redis:
    host: 192.168.9.96
    port: 6379
    password: RdsBhw@2019
  cache:
    type: redis

  session:
    store-type: redis
  messages:
    basename: messages
  datasource:
    url: jdbc:postgresql://192.168.9.100:5432/bhwdb
    username: postgres
    password: Bhw@2019
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true
  data:
    jpa:
      repositories.enabled: true
  security:
    sessions: NEVER
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    jp.bizhighway.order: DEBUG
  file: service-order.log